# ===== Build assets =====
FROM node:20-alpine AS build
WORKDIR /app

# --- 환경 변수 전달 ---
ARG VITE_SERVER_ORIGIN
ENV VITE_SERVER_ORIGIN=$VITE_SERVER_ORIGIN

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# ===== Nginx serve =====
FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]